### PR TITLE
assignment3

### PR DESCRIPTION
**Pull request by Ginny1209**
## Checklist
- [ ] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by Ginny1209** [comment]
cannot figure out the last part-expaliner

**Comment by ananyajha2000** [comment]
Hi, I cannot mark it complete until you finish all parts. Please reach out to Learning Support for help and resubmit when complete.

**Comment by Ginny1209** [comment]
resubmit

**Comment by Ginny1209** [comment]
> Hi, I cannot mark it complete until you finish all parts. Please reach out to Learning Support for help and resubmit when complete.

Hi, did you find my new PR on assignment 3( scaling to production) Thank you.

**Pull request closed without merging**
